### ISSUE TITLE
Maps get clipped in small screen landscape view

### ISSUE THREAD

**Issue by lindamood** [nprapps/lookatthis#1044]
![screen shot 2015-11-11 at 9 46 37 am](https://cloud.githubusercontent.com/assets/1319852/11093610/3c24c336-8859-11e5-8680-9b90cc2462bd.png)

**Comment by TylerFisher** [comment]
Yeah... hm. Not entirely sure what to do about this.

**Comment by lindamood** [comment]
Just flagging it so we know about it. The possible solutions to address the clipping aren't worth the level of effort, IMO. The way the story is set up I think there isn't much of a reason users would browse the story in landscape.
