### ISSUE TITLE
font awesome 403 error on production

### ISSUE THREAD

**Issue by lindamood** [nprapps/lookatthis#399]
Can you help me troubleshoot this? I remember you all had a Font Awesome issue when you were building the look post framework.

Failed to load resource: the server responded with a status of 403 (Forbidden) http://apps.npr.org/lookatthis/posts/veterans/css/font/fontawesome-webfont.woff?v=4.0.3

Failed to load resource: the server responded with a status of 403 (Forbidden) http://apps.npr.org/lookatthis/posts/veterans/css/font/fontawesome-webfont.ttf?v=4.0.3

Failed to load resource: the server responded with a status of 403 (Forbidden) http://apps.npr.org/lookatthis/posts/veterans/js/lib/ZeroClipboard.swf?noCache=1410968509248

Failed to load resource: the server responded with a status of 403 (Forbidden) http://apps.npr.org/lookatthis/posts/veterans/css/font/fontawesome-webfont.svg?v=4.0.3#fontawesomeregular

**Comment by sandeepnegi1996** [comment]
hi @lindamood 

i am facing the same issue : GET https://rb-wam-q.bosch.com/fontawesome-webfont.b06871f281fee6b241d6.ttf net::ERR_ABORTED 403 (Forbidden)


and the i have checked the referer header it is pointing to bundle.css so you know solution for this one
