### ISSUE TITLE
OG tags on individual posts are too general

### ISSUE THREAD

**Issue by alykat** [nprapps/lookatthis#493]
They refer to the overall tumblr rather than to the post in question. Noted while trying to share Wes's "faces in things" post on Facebook.

![image](https://cloud.githubusercontent.com/assets/491318/4983922/fa8ff562-691e-11e4-9c9d-22d62294177c.png)

http://lookatthisstory.tumblr.com/post/102023006747/the-joy-of-finding-faces-in-things

**Comment by TylerFisher** [comment]
Done in a7a8b98b7f20748a472f57b0109ff06c438acdd1
