### ISSUE TITLE
Test embedded Tweet template

### ISSUE THREAD

**Issue by oneillclaire** [nprapps/lookatthis#685]
Here's his storified Twitter story:
http://chirpstory.com/li/2128

Many of the original photo Tweets appear to be broken at this point, so maybe we ultimately fake it. Or paraphrase with narration and cut the Tweets (potentially the easiest/best option).

**Comment by TylerFisher** [comment]
Yeah, a lot of the photos are broken, and the twitpics don't come with the embed. It's possible to do this, but I think we can do better.

![screen shot 2015-02-09 at 11 59 36 am](https://cloud.githubusercontent.com/assets/1077075/6110906/fb8d2f36-b052-11e4-9ce8-2874544eb4d1.png)

**Comment by oneillclaire** [comment]
@TylerFisher Hm yeah ... Ok, lemme just try ditching the Tweets and paraphrasing, and see how it feels...

**Comment by TylerFisher** [comment]
This is working if we decide to use it.
