### ISSUE TITLE
Multivariate Testing: final card call to action

### ISSUE THREAD

**Issue by livlab** [nprapps/lookatthis#717]
### Purpose ###
Visual stories have greater reach than most stories. This test explore models that help user conversion (various types) for greater engagement with users who view these stories.

### Recipes ###
* There is no control; all recipes are exploratory
* Recipe A: Follow Us #713 
* Recipe B: Support Public Radio #714 
* Recipe C: Like Story and Follow Us #716 
* Recipe D: Like Story and Support Public Radio #715 

### Traffic ###
* Estimated total traffic in the 100k unique users range
* Full split between all recipes (25% each).
* Start and end dates TBD

**Comment by TylerFisher** [comment]
This reads more as a ticket for evaluating the results of the test, which I like. Reopening.

**Comment by livlab** [comment]
Yes, I've used it to keep information about test progress and details of audience split. Helps to design the next test!
