### ISSUE TITLE
Break Follow Button Click between like-story and no-like-story

### ISSUE THREAD

**Issue by livlab** [nprapps/lookatthis#729]
Support Button Click is reported with the split of like-story x not-like story, meaning, how many clicked support after seeing the question or being directly shown that option.

How can we do the same break-down for Follow Button Click so we can know for each social media link what's the split between people who saw those options right away and those who saw the question first?

http://cron-staging.nprapps.org/carebot/report/look-brother-and-sister-love/all-time/

**Comment by TylerFisher** [comment]
Unfortunately, unbeknownst to us, Google removed support for custom variables in event tracking. We don't have a way of knowing this.

**Comment by eads** [comment]
ha, didn't we talk about this? they removed custom variables quite some time ago.

**Comment by TylerFisher** [comment]
Basically @onyxfish and I were like, 
![jay-z](https://cloud.githubusercontent.com/assets/1077075/6231844/20bec73a-b696-11e4-8936-0eedf44d1894.png)

We should have believed you.
