### ISSUE TITLE
Figure out what to do about Up Next 

### ISSUE THREAD

**Issue by beckylettenberger** [nprapps/lookatthis#850]

**Comment by lindamood** [comment]
Let's use the up next screen design from Spacepix. 

Questions:

- If we include the intro screen after the title screen, I'm thinking the back button should link to the intro? @TylerFisher let's discuss this.

- Did we learn anything from the 'Did you like this story?' prompt at the end of the bus station story? If the results were inconclusive, let's ask the same question again followed by a 'share on Facebook button'. Or... In lieu of a facebook button, another option would be to include a 'view more stories like this' link that points to http://lookatthisstory.tumblr.com/tagged/stories/ If there was statistically significant traffic (wishful thinking) , it would be helpful to see what story users choose based on the story they were previously on.

- What project should we add to up next? Spacepix feels too similar, I think. I recommend http://apps.npr.org/lookatthis/posts/harrisloves/ or http://apps.npr.org/lookatthis/posts/bus-station/ but defer to @oneillclaire on that.

**Comment by TylerFisher** [comment]
Still need an answer for Up Next, but I don't think we got conclusive results from our last test, so let's run that again.

**Comment by TylerFisher** [comment]
done
