### ISSUE TITLE
Mobile: Ambient doesn't start upon leaving the video

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/lookatthis#894]
Perhaps because the native media player is already being used.

**Comment by TylerFisher** [comment]
I tried to have the slide advance automatically after the video ended. On mobile, that means the ambient player can't start because it is not a touch event triggering the slide change. This leaves us with two options:

1. Don't automatically advance the slide, just close the fullscreen player and make the user click to the next slide manually.
2. Don't have ambient audio immediately after the video.

I lean towards option 1, but either way, we're not really going to achieve the smooth transition from video to audio we were hoping for on mobile (we still can on desktop though)

**Comment by lindamood** [comment]
Yeah, leaning toward option 1 as well. The thing we need to figure out is the right way to alert users to the fact that the video is not the totality of the experience. Is a right arrow enough?  Looking at this example, I think the 'skip intro' text helps.

![screen shot 2015-06-16 at 5 09 49 pm](https://cloud.githubusercontent.com/assets/1319852/8194579/890463e2-144a-11e5-924a-08045ae92536.png)

**Comment by TylerFisher** [comment]
Okay. That's what's happening now, so I'll close this and open new tickets around figuring out the mobile design of the intro video slide.
