### ISSUE TITLE
Mobile design for intro video slide

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/lookatthis#896]
* How do we signal to users that the video is not the whole experience?
* What should the slide look like when you finish the video?
* Box in the video so it is not the full width of the screen

**Comment by lindamood** [comment]
just a reminder of another mobile video approach we've used in the past
![planet_money_makes_a_t-shirt](https://cloud.githubusercontent.com/assets/1319852/8214011/46172d80-14f4-11e5-9947-cf0e18556e1e.png)
