### ISSUE TITLE
Better post template building

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/lookatthis#908]
Maybe an interactive prompt in the post builder, asking things like:

* Do you need audio? (maybe this is divided between narrative/ambient, gives you templates for narrative) [gives you jplayer + barebones audio.js file]
* Do you need filmstrips? [gives you filmstrip templates + barebones filmstrip.js file]

**Comment by eads** [comment]
Chatted with @TylerFisher about this... one option would be to include all the libraries all the time, but control them with a couple of spreadsheet flags: use_audio = 1 would enable a block in `_base.html` that loads the right JS, etc.
