### ISSUE TITLE
Disable right arrow while the video is playing 

### ISSUE THREAD

**Issue by beckylettenberger** [nprapps/lookatthis#939]

**Comment by TylerFisher** [comment]
Okay, so here's my dilemma with the arrows:

1. Disabling just the right arrow leaves only the left arrow, which implies that the video is the end of the content.
2. Disabling both arrows gives you no way to get back to the titlecard. Not that there's any good reason to go back there, but it feels user-hostile.

**Comment by beckylettenberger** [comment]
Makes total sense. Let's keep em!
