### ISSUE TITLE
Perhaps a more subtle skip prompt? 

### ISSUE THREAD

**Issue by oneillclaire** [nprapps/lookatthis#945]
<img width="1137" alt="screen shot 2015-07-10 at 9 32 20 am" src="https://cloud.githubusercontent.com/assets/2932380/8619656/c7448b92-26e6-11e5-98c3-e39ab1c4715e.png">

as opposed to 

<img width="1177" alt="screen shot 2015-07-10 at 9 34 12 am" src="https://cloud.githubusercontent.com/assets/2932380/8619669/df3727aa-26e6-11e5-9fe9-3bedebb814d7.png">

**Comment by TylerFisher** [comment]
Done in 961b6688f071e63518428aa42e19afac5d8f18e8
