### ISSUE TITLE
hide right/arrow paddle til end of video?

### ISSUE THREAD

**Issue by oneillclaire** [nprapps/lookatthis#946]
did you already try this? cant remember if I ticketed it...

**Comment by beckylettenberger** [comment]
Yeah, see #939 and #940, 
@TylerFisher and I talked about it the other day and I agree it feels a little funny. If we disable the right arrow, does that imply there's nothing but the video?

**Comment by oneillclaire** [comment]
Hm. yeah ... tho ... is that bad?

**Comment by TylerFisher** [comment]
Hidden until mousemove.
