### ISSUE TITLE
Subtitles and progress bar are clashing

### ISSUE THREAD

**Issue by oneillclaire** [nprapps/lookatthis#947]
Should we tweak the CSS or should I just move the subtitles? 

<img width="1316" alt="screen shot 2015-07-10 at 9 36 58 am" src="https://cloud.githubusercontent.com/assets/2932380/8619737/53aed65a-26e7-11e5-9fd3-343c674f9c47.png">

**Comment by TylerFisher** [comment]
Fixed by hiding the controls except on mouse move.
