### ISSUE TITLE
iOS Safari triggers resizes all the time and that messes up overflowed content

### ISSUE THREAD

**Issue by TylerFisher** [nprapps/lookatthis#962]
sigh

**Comment by eads** [comment]
can you throttle it?

On Tue, Jul 14, 2015 at 5:05 PM, Tyler Fisher <notifications@github.com>
wrote:

> sigh
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nprapps/lookatthis/issues/962>.
>



-- 
David Eads | http://recoveredfactory.net

"Medical statistics will be our standard of measurement: we will weigh life
for life and see where the dead lie thicker, among the workers or among the
privileged." -- Rudolf Virchow
