### ISSUE TITLE
I think we're going to need mobile crops on this one.

### ISSUE THREAD

**Issue by lindamood** [nprapps/lookatthis#978]
let's make an inventory of images that we'll  need mobile crops for. 

![the_lost_casualties_of_yemen_s_war](https://cloud.githubusercontent.com/assets/1319852/9340016/6c03f116-45bb-11e5-929f-12bf3831491d.jpg)

And existing crops that don't work on desktop. like this one-- can we crop it a little tighter so the focus is on the little girl.

![the_lost_casualties_of_yemen_s_war](https://cloud.githubusercontent.com/assets/1319852/9340051/ab24b04c-45bb-11e5-8d44-25d76863f3a7.jpg)

**Comment by beckylettenberger** [comment]
what dimension should I crop these?

**Comment by TylerFisher** [comment]
We usually do squares, not sure what dimensions we've used in the past, but I'd say like 800px wide is probably good.

**Comment by beckylettenberger** [comment]
word, thanks!
